Improve Stack Trace tracking for Instrumentation
Netflix/archaius pull request #701
Opened 2024-02-06 01:54 UTC by akang31

Add archaius_stack_trace_enabled_properties which allows tracking of individual properties (instead of all of them) so we can reduce runtime impact of calculating stack traces. We can use this to only track some unused global fast properties.

This new set will also maintain all the properties associated with specific call sites, in case we are calling several.

Also surfaces these Maps as they were only accessible via the debugger before

2024-02-06 18:38 UTC, rgallardo-netflix requested changes

2024-02-06 18:38 UTC, rgallardo-netflix commented on archaius-core/src/main/java/com/netflix/config/ConcurrentCompositeConfiguration.java
> +            boolean isTrackedProperty = !stackTraceEnabledProperties.isEmpty() && stackTraceEnabledProperties.contains(key);
No need to check separately if the set is empty. A call to `Collections.emptySet().contains()` is just as fast as `Collections.emptySet().isEmpty()`

2024-02-06 18:38 UTC, rgallardo-netflix commented on archaius-core/src/main/java/com/netflix/config/ConcurrentCompositeConfiguration.java
> +        if (properties == null) {
Since we already have Guava available here, let's leverage its `Splitter` and `ImmutableSet` classes:
```
if (properties == null) {
 return Collections.emptySet();
}

return ImmutableSet.copyOf(Splitter.on(',').trimResults().omitEmptyStrings().split(properties));
```
This removes the possible confusion that would come from people putting spaces or line breaks in the system property and uses a read-only set implementation with a very very efficient `contains()`.

2024-02-06 18:38 UTC, rgallardo-netflix commented on archaius-core/src/main/java/com/netflix/config/ConcurrentCompositeConfiguration.java
> +                    stackTraces.merge(trace, 1, (v1, v2) -> v1 + 1);
duplicate?

2024-02-06 18:59 UTC, akang31 commented on archaius-core/src/main/java/com/netflix/config/ConcurrentCompositeConfiguration.java
> +        if (properties == null) {
How I've missed ImmutableSet.of()... :') 

Thanks for pointing this out, updated to this

2024-02-06 18:59 UTC, akang31 commented on archaius-core/src/main/java/com/netflix/config/ConcurrentCompositeConfiguration.java
> +            boolean isTrackedProperty = !stackTraceEnabledProperties.isEmpty() && stackTraceEnabledProperties.contains(key);
Ah right, I thought this was a HashSet for some reason, removed the empty check

2024-02-06 18:59 UTC, akang31 commented on archaius-core/src/main/java/com/netflix/config/ConcurrentCompositeConfiguration.java
> +                    stackTraces.merge(trace, 1, (v1, v2) -> v1 + 1);
Resolved offline

2024-02-07 00:47 UTC, rgallardo-netflix approved these changes

2024-02-07 18:34 UTC, merged